### ISSUE TITLE
Hello！ some problems happened here

### ISSUE THREAD

**Issue by HenkorDemo** [edwinpalegre/EE8204-ResUNet#2]
When I run train.py, the error could not broadcast input array from shape (224,224) into shape (224,224,3) always pops up. The error is in train.py line 58 and utils.py line 98, but I don’t The original code has not been changed, so I don’t know how to deal with it, can you help me answer it?

**Comment by edwinpalegre** [comment]
Hi Henkor,

Have you ensured that you've downloaded the right dependencies and versions for the code? If so, please download the recently commited branch of 5layer-resunet. I've just verified that it was working on my end. It should work for you as well

**Comment by HenkorDemo** [comment]
OK！Thank You! I will try it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edwinpalegre/EE8204-ResUNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月20日(星期天) 上午10:41
收件人:&nbsp;"edwinpalegre/EE8204-ResUNet"<EE8204-ResUNet@noreply.github.com&gt;;
抄送:&nbsp;"994318249"<994318249@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [edwinpalegre/EE8204-ResUNet] Hello！ some problems happened here (#2)





 
Hi Henkor,
 
Have you ensured that you've downloaded the right dependencies and versions for the code? If so, please download the recently commited branch of 5layer-resunet. I've just verified that it was working on my end. It should work for you as well
